---
name: NixOS CI test workflow

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [nix, aarch64-linux]

    steps:
      - uses: actions/checkout@v2

      - name: run
        run: nix run
