---
name: Nix CI Test Workflow

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [aarch64-linux]
    runs-on: [nix, "${{ matrix.os }}"]

    steps:
      - uses: actions/checkout@main

      - name: run
        run: nix run
